[tool.ruff]
line-length = 88
select = ["E", "F", "W", "C", "Q", "B", "S", "D", "ANN", "PT", "PLR", "PTH", "RUF"]

# Many tests intentionally use simple asserts and lack docstrings/type-annotations.
# Relax a set of rules for tests to keep focus on integration code quality.
per-file-ignores = { "tests/*" = ["S101", "D100", "D101", "D102", "D103", "ANN201", "ANN204", "ANN202", "ANN001", "ANN203", "ANN200", "E501", "PTH107", "PT015", "PT017", "PT018", "PLR2004"] }
